### Softmax

Pytoch softmax from tutorial https://www.youtube.com/watch?v=7q7E91pHoW4

In [16]:
import torch
import numpy as nm

x = torch.tensor([2.0, 1.0, 0.1])
outputs = torch.softmax(x, dim = 0)
print(outputs.data)

#way to retrieve raw value from tensor
print(outputs.data[0].item())

#tensor column dim
print(outputs.size()[0])

tensor([0.6590, 0.2424, 0.0986])
0.6590011715888977
3


### Cross-Entropy handwritten
Cross-entropy is always used to measure loss for values after softmax(!)

In [27]:
def crossEntropy(y, y_pred):
    num = (-1) / y_pred.size()[0]
    print(num)
    sum = 0
    for i in range(3):
        sum += y.data[i].item() * nm.log(y_pred.data[i].item())
    print(sum)
    print(num * sum)
    return num * sum

def crossEntropy_NM(y, y_pred):
    loss = -nm.sum(y * (nm.log(y_pred)))
    return loss

y = torch.tensor([1, 0, 0])
outputs = torch.tensor([0.7, 0.2, 0.1])

print("y class: ")
print(y.data)
print("y pred: ")
print(outputs.data)
resCE = crossEntropy(y, outputs.data)

y1 = nm.array([1, 0, 0])
y_pred1 = nm.array([0.7, 0.2, 0.1])

print("____")
print(crossEntropy_NM(y1, y_pred1))

y class: 
tensor([1, 0, 0])
y pred: 
tensor([0.7000, 0.2000, 0.1000])
-0.3333333333333333
-0.35667496096863105
0.11889165365621035
____
0.35667494393873245


### PyTorch CrossEntropy (predicting one class)

После вариантов, написанных вручную, попробуем воспользоваться встроенными возможностями PyTorch для рассчета cross-entropy.

In [4]:
import torch

loss = torch.nn.CrossEntropyLoss()

#1 class 
y1 = torch.tensor([0])

#2 class
y2 = torch.tensor([1])

#nsamples x nclasses = 1x3

#correct for 1 class
y_pred1 = torch.tensor([[2.0, 1.0, 1.0]])

#correct for 2 class
y_pred2 = torch.tensor([[2.0, 4.0, 1.0]])

print("Checking y_pred1 and y_pred2...")
print("Let's calculate which one of them closer to 1 class!")
print("----")
print("Loss for y_pred1 and 1 class: ")
loss11 = loss(y_pred1, y1)
_, max11 = torch.max(y_pred1, 1)
print(loss11)
print(max11)
print("Loss for y_pred2 and 1 class: ")
loss12 = loss(y_pred2, y1)
_, max12 = torch.max(y_pred2, 1)
print(loss12)
print(max12)
print()
print("Checking y_pred1 and y_pred2...")
print("Let's calculate which one of them closer to 2 class!")
print("----")

loss21 = loss(y_pred1, y2)
_, max21 = torch.max(y_pred1, 1)
print(loss21)
print(max21)
loss22 = loss(y_pred2, y2)
_, max22 = torch.max(y_pred2, 1)
print(loss22)
print(max22)

Checking y_pred1 and y_pred2...
Let's calculate which one of them closer to 1 class!
----
Loss for y_pred1 and 1 class: 
tensor(0.5514)
tensor([2.])
Loss for y_pred2 and 1 class: 
tensor(2.1698)
tensor([1])

Checking y_pred1 and y_pred2...
Let's calculate which one of them closer to 2 class!
----
tensor(1.5514)
tensor([0])
tensor(0.1698)
tensor([1])


### PyTorch for cross-entropy (predicting batch)

In [47]:
loss = torch.nn.CrossEntropyLoss()


y = torch.tensor([2, 0, 1])
#nsamples x nclasses = 3x3

y_pred_good = torch.tensor([[0.1, 1.0, 3.0], [1.0, 0.3, 0.3], [2.0, 4.0, 1.0]])
y_pred_bad = torch.tensor([[1.1, 0.9, 3.0], [0.1, 3.3, 0.3], [2.0, 0.6, 1.0]])

loss_good = loss(y_pred_good, y)
print(loss_good)
loss_bad = loss(y_pred_bad, y)
print(loss_bad)
print("Check which one loss is closer to 0 - that's better result!")

tensor(0.3446)
tensor(1.8021)
Check which one loss is closer to 0 - that's better result!
